version: '3'

services:
  client:
    build: client
    container_name: client
    ports:
      - '8080:8080'
    networks:
      - app-network

  server:
    build: server
    container_name: server
    environment:
      APP_NAME: tbl_csdl
      PORT: 3000
      DB_URI: mongodb://mongo:27017/tbl_csdl 
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    command: mongod --quiet --logpath /dev/null
    networks:
      - app-network

networks:
  app-network:
    driver: bridge